lend_engine:
  site_url: https://lammlibrary.lend-engine-app.com
  api_url: https://lammlibrary.lend-engine-app.com/api/2/
  image_url: https://s3-us-west-2.amazonaws.com/lend-engine/lammlibrary/large/
options:
  sticker_sizes:
  - - 40
    - 30
  - - 50
    - 30
  - - 50
    - 50
  - - 80
    - 50
  current_sticker_size:
  - 80
  - 50
  current_site: Lancaster Community Makerspace
  sticker_size:
  - 50
  - 30
stickers:
  show_site: true
  organization: Part of BayShare - bayshare.org.uk
